# Generated by Django 4.0.1 on 2022-02-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='authors',
            field=models.CharField(default='Ridhi Ratan, Abhishek Parmar, Geetanshu Arsiya', max_length=200),
            preserve_default=False,
        ),
    ]
